studenthelp/website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_required, current_user
from sqlalchemy import func
import os
from azure.storage.blob import BlobServiceClient
from . import db
import json
from .models import User, Credit, Honors, Volunteering, Job, Recommendation
from datetime import datetime
from datetime import date, datetime
from .keys import connect_str, account_key


container_name = "volunteerinfo"

views = Blueprint('views', __name__)

ROWS_PER_PAGE = 5

#******************************** Home  *************************************************************
@views.route('/', methods=['GET','POST'])
@login_required
def home():
    hours=0
   # maxid = db.session.query(func.max(Volunteering.volunteer_seq))
    
    volunteerings = Volunteering.query.filter_by(user_id=current_user.id)

    for volunteering in volunteerings:
        hours+=volunteering.hours
    awardnum =0
    creditnum=0

    awards = Honors.query.filter_by(user_id=current_user.id)
    credits= Credit.query.filter_by(user_id=current_user.id)
    for award in awards:
        awardnum+=1
    for credit in credits:
        creditnum+=credit.credit_unit
    
    return render_template("home.html", user=current_user, hours=hours, creditnum=creditnum, awardnum=awardnum)
    

#********************************Display Function for Volunteering ***************************************** 
@views.route('/volunteering', methods=['GET','POST'])
@login_required
def volunteering():   
# this function is to display volunteering information. It selects all data from Volunteer table 
# for the logged in user
    try:                                                                                                 
        page = request.args.get('page', 1, type=int)
        print("hello")
        print(current_user.id)
        
        volunteerings = Volunteering.query.filter_by(user_id=current_user.id).paginate(page=page,per_page=ROWS_PER_PAGE)
        print('rendering job')
        return render_template("volunteering.html", user=current_user, volunteerings=volunteerings)
        
    except Exception as exc:
        print(exc)        
    except:
        flash("An error has occured", category="error")

#********************************Display Function for jobs ********************************************
@views.route('/job', methods=['GET','POST'])
@login_required
def job():   
# this function is to display Job information. It selects all data from Job table 
# for the logged in user
    try:                                                                                                 
        page = request.args.get('page', 1, type=int)
        print("hello")
        print(current_user.id)
        
        jobs = Job.query.filter_by(user_id=current_user.id).paginate(page=page,per_page=ROWS_PER_PAGE)
        print('rendering job')
        return render_template("job.html", user=current_user, jobs=jobs)
        
    except Exception as exc:
        print(exc)        
    except:
        flash("An error has occured", category="error")

#********************************Display Function for Recommendation ********************************************

@views.route('/recommendation', methods=['GET','POST'])
@login_required
def recommendation():   
# this function is to display Recommendation information. It selects all data from Recommendation table 
# for the logged in user

    try:                                                                                                 
        page = request.args.get('page', 1, type=int)
        print("hello")
        print(current_user.id)

        recommendations = Recommendation.query.filter_by(user_id=current_user.id).paginate(page=page,per_page=ROWS_PER_PAGE)
        print('rendering recommendation')
        return render_template("recommendations.html", user=current_user, recommendations=recommendations)
        
    except Exception as exc:
        print(exc)        
    except:
        flash("An error has occured", category="error")

#********************************Display Method for Awards ********************************************
@views.route("/awards", methods=['GET', 'POST'])
@login_required
def showawards():
# this function is to display Awards information. It selects all data from Awards table 
# for the logged in user

    page = request.args.get('page', 1, type=int)
    print("hello")
    print(current_user.id)
        
    awards = Honors.query.filter_by(user_id=current_user.id).paginate(page=page,per_page=ROWS_PER_PAGE)
        
    return render_template("awards.html", user=current_user,awards=awards)

#********************************Display Function for Credits ********************************************
@views.route("/show-credit", methods=['GET', 'POST'])
@login_required
def showcredit():
# this function is to display Credits information. It selects all data from Credits table 
# for the logged in user

    page = request.args.get('page', 1, type=int)
    print("hello")
    print(current_user.id)
        
    credits = Credit.query.filter_by(user_id=current_user.id).paginate(page=page,per_page=ROWS_PER_PAGE)
    return render_template("showcredit.html", user=current_user,credits=credits)


#********************************Delete Function for Volunteering ********************************************
@views.route('/delete-volunteering', methods=['GET','POST'])
@login_required
def delete_volunteering():
# this function is to delete volunteering information. It deletes the selected row from Volunteering table 
# for the logged in user

    try:
        print('inside delete_volunteering')
        volunteeringid = request.args.get('volunteeringid')
        print(volunteeringid)
        volunteerings = Volunteering.query.get(volunteeringid)
        if volunteerings.user_id == current_user.id:
                print('success 2')
                db.session.delete(volunteerings)
                db.session.commit()
                print('deleted')
                return redirect(url_for('views.volunteering')) 
        
        return redirect(url_for('views.volunteering')) 
    except:
        flash("An error has occured", category="error") 

#********************************Delete Function for Jobs ********************************************
@views.route('/delete-job', methods=['GET','POST'])
@login_required
def delete_job():
# this function is to delete Job information. It deletes the selected row from Job table 
# for the logged in user

    try:
        print('inside delete_job')
        jobid = request.args.get('jobid')
        print(jobid)
        jobs = Job.query.get(jobid)
        if jobs.user_id == current_user.id:
                print('success 2')
                db.session.delete(jobs)
                db.session.commit()
                print('deleted')
                return redirect(url_for('views.job')) 
        
        return redirect(url_for('views.job')) 
    except:
        flash("An error has occured", category="error") 

#********************************Delete Function for Recommendation ********************************************

@views.route('/delete-recommendation', methods=['GET','POST'])
@login_required
def delete_recommendation():
# this function is to delete Recommendation information. It deletes the selected row from Recommendation table 
# for the logged in user

    try:
        print('inside delete_recommendation')
        recommendationid = request.args.get('recommendationid')
        print(recommendationid)
        recommends = Recommendation.query.get(recommendationid)
        if recommends.user_id == current_user.id:
                print('success 2')
                db.session.delete(recommends)
                db.session.commit()
                print('deleted')
                return redirect(url_for('views.recommendation')) 
        
        return redirect(url_for('views.recommendation')) 
    except:
        flash("An error has occured", category="error") 

#********************************Delete Function for Credits ********************************************
@views.route('/delete-credit', methods=['GET','POST'])
@login_required
def delete_credit():
# this function is to delete Credit information. It deletes the selected row from Credit table 
# for the logged in user

    try:
        print('inside delete_credit')
        creditid = request.args.get('creditid')
        print(creditid)
        credits = Credit.query.get(creditid)
        if credits.user_id == current_user.id:
                print('success 2')
                db.session.delete(credits)
                db.session.commit()
                print('deleted')
                return redirect(url_for('views.showcredit')) 
        
        return redirect(url_for('views.showcredit')) 
               # return render_template("volunteering.html", user=current_user, volunteerings=volunteerings)
        #return jsonify({}
        #return render_template("volunteering.html", user=current_user, volunteerings=volunteerings)
    except:
        flash("An error has occured", category="error") 


#********************************Delete Function for Awards ********************************************
@views.route('/delete-award', methods=['GET','POST'])
@login_required
def delete_award():
# this function is to delete Award information. It deletes the selected row from Awards table 
# for the logged in user

    try:
        print('inside delete_award')
        awardid = request.args.get('awardid')
        print(awardid)
        honors = Honors.query.get(awardid)
        if honors.user_id == current_user.id:
                print('success 2')
                db.session.delete(honors)
                db.session.commit()
                print('deleted')
                return redirect(url_for('views.showawards')) 
        
        return redirect(url_for('views.showawards')) 

studenthelp/website/templates/addaward.html
{% extends "base.html" %} {% block title %}Add Student{% endblock %}Add Student{% block content %}
<br />    
    <form method="POST">
        <h3 align="center">
            Add Awards and Honors
        </h3>
        <div class="form-group">
            <label for="orgName">Organization Name:</label>
            <input 
                type="text" 
                class="form-control" 
                id="orgName" 
                name="orgName" 
                placeholder="Enter Organization"
            />
        </div>
        <div class="form-group">
            <label for="honorName">Award/Honor name:</label>
            <input 
                type="text" 
                class="form-control" 
                id="honorName" 
                name="honorName" 
                placeholder="Enter name"
            />
        </div>
        <div class="form-group">
            <label for="receivedDate">Date received:</label>
            <input 
                type="date" 
                class="form-control" 
                id="receivedDate" 
                name="receivedDate" 
                placeholder="Enter date"
            />
        </div>
        <div class="form-group">
            <label for="level">Level(Regionals, State, National, etc...):</label>
               <select name="level" id="level" class="form-control" > 
                <option value="School">School</option>
                <option value="Regional">Regional</option>
                <option value="State">State</option>
                <option value="National">National</option>
                <option value="International">International</option>
              </select>

        </div>
        <div class="form-group">
            <label for="description">Description:</label>
            <input 
                type="text" 
                class="form-control" 
                id="description" 
                name="description" 
                placeholder="Enter description"
            />
        </div>
      
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endblock %}
    

studenthelp/website/templates/addcredit.html
{% extends "base.html" %} {% block title %}Add Payment{% endblock %}{% block content
    %} 

<br />
<form method="POST">
    <h3 text-align="center">Add A HighSchool Credit </h3>
    <br />
    <div class="form-group">
    <label for="courseName">Course Name:</label>
    <input 
        type="text" 
        class="form-control" 
        id="courseName"
        name="courseName" 
        placeholder="Enter course"
    />
<br />
    <div class="form-group">
        <label for="creditUnit">Credit Unit(0.5 or 1):</label>
        <input 
            type="number" 
            class="form-control" 
            id="creditUnit" 
            name="creditUnit" 
            step="any" 
            placeholder="Enter unit"
        />
    <br />
    <div class="form-group">
            <label for="weightage">Weightage:</label>
            <input 
                type="text" 
                class="form-control" 
                id="weightage" 
                name="weightage" 
                placeholder="Enter Weightage"
        />
    <br />
    <div class="form-group">
        <label for="provider">Provider(School, College, etc..):</label>
        <input
            type="text"
            step="any" 
            class="form-control" 
            id="provider" 
            name="provider" 
            placeholder="Enter provider"  
        />
    <br />
    <div class="form-group">
        <label for="classification">Classification(Math, Foriegn Language, etc..):</label>
        <input
            type="text"
            step="any" 
            class="form-control" 
            id="classification" 
            name="classification" 
            placeholder="Enter Classification"  
        />
    <br />
    <div class="form-group">
        <label for="score">Score(Number):</label>
        <input
            type="number"
            step="any" 
            class="form-control" 
            id="score" 
            name="score" 
            step="any" 
            placeholder="Enter score"  
        />
    <br />
    <div class="form-group">
        <label for="grade">Grade(letter):</label>
        <input
            type="text"   
            step="any" 
            class="form-control" 
            id="grade" 
            name="grade" 
            placeholder="Enter grade"  
        />
    <br />
</form>
<button type="submit" class="btn btn-primary">Add Credit</button>

{% endblock %}

studenthelp/website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
        crossorigin="anonymous"
      />
      <linka
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous"
      />

      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
      
      <title>{% block title %}Home{% endblock %}</title>
    </head>
    <style>
        body {
            background-image: url('https://th.bing.com/th/id/R.b179474d4fa04e9df880ef0445697ee5?rik=v7kEGZ6PWclRJQ&riu=http%3a%2f%2fgetwallpapers.com%2fwallpaper%2ffull%2f5%2fc%2f3%2f1072806-large-cream-colored-wallpaper-2560x1440.jpg&ehk=rWQhLJNfK0N7alVZ9aBW%2bv9c%2bPASYbn8wuBAyj0UOIw%3d&risl=&pid=ImgRaw&r=0');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
        }
        .square{
            background-color: rgb(139, 137, 137);
            border-color: rgb(52, 51, 51);
            text-align: center;
            float:right;
            width: 50px;
            height: 10px;
            
        }
        .dropdown-options{
    display: none;
    position: absolute;
    overflow: auto;
  }
.dropdown-content {
  display: none;
  position: absolute;
  width: 120px;
  overflow: auto;
  z-index: 4;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  background-color: white
  
  
}


.dropdown{
  display: inline-block;
  position: relative;
}
.dropdown::selection .dropdown-options{
    display: block;
}
.test:after {
    content: '\2807';
    font-size: 25px;
  }

.dropdown:hover .dropdown-content {
  display: block;
}
    </style>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <button 
                class="navbar-toggler" 
                type="button" 
                data-toggle="collapse"
                data-target="#navbar"
            >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id = "navbar">
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                    <a class="nave-item nav-link" id="home" href="/">   Home</a>
                    <a class="nave-item nav-link" id="logout" href="/logout">Logout</a>
                    <a class="nave-item nav-link" id="add_volunteering" href="/volunteering">Volunteering</a>
                    <a class="nave-item nav-link" id="credit" href="/show-credit">Courses and Credits</a>
                    <a class="nave-item nav-link" id="awards" href="/awards">Honors and Awards </a>
                    <a class="nave-item nav-link" id="job" href="/job">Jobs </a>
                    <a class="nave-item nav-link" id="recommendation" href="/recommendation">Recommendations </a>
                    {% else %}  
                    <a class="nave-item nav-link" id="login" href="/login">Login</a>
                    <a class="nave-item nav-link" id="signUp" href="sign-up">Sign Up</a>
                    
                    {% endif %}
                <div>
            </div>
        </nav>
        <h1 style="color:blue"> <center> My High School Organizer </center></h1>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
            {% if category == 'error' %}
            <div class="alert alert-danger alter-dismissable fade show">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% else %}
            <div class="alert alert-success alter-dismissable fade show">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>  
            {% endif %}      
            {% endfor %}
        {% endif %}
        {% endwith %}

        <div class="container">{% block content %}{% endblock %} 
        </div>
        <script
            src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"
        ></script>
      <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
      ></script>
      <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
      ></script>
  
      <script
        type="text/javascript"
        src="{{ url_for('static', filename='index.js') }}"
      ></script>
    </div>

    {% block modal %}{% endblock %}
    <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap5.js"></script>
    
    
    </body>
    {% block script %}<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>{% endblock %}
    
</html>

studenthelp/website/templates/home.html
{% extends "base.html" %}{% block title %}Volunteering{% endblock %}{% block content  
    %} 
<style>
strong span { 
    background-color: green; 
}
.circle {
  height: 200px;
  width: 200px;
  background-color: #03743f;
  line-height: 200px;
  border-radius: 50%;
  border-color: aliceblue;
}
.rounded-box {
    background-color: #2ba975;
    border-radius: 20px;
    padding: 20px;
    width: 350px;
    height: 450px;
    box-shadow: 0px 0px 10px #888;
    font-size: 50px;
    
}
.square {
  height: 25px;
  width: 25px;
  background-color: #55555500;
  float:left;
}

</style>
  
  <br />
      <h2 ><center>Welcome, {{user.first_name}} {{user.last_name}}!</center></h2>
      
  <br />

  <div class="rounded-box" style="float:left;">
    <center style="color:rgb(255, 255, 255);">
        <h1>You have...</h1>
    </center>
    <center><div class="circle"><center style="color:aliceblue">{{"%.1f"|format(hours)}}</center></div></center>
    <center style="color:rgb(255, 255, 255);">
        <h1>hour(s) of volunteering!!</h1>
    </center>
</div>
<div class="square" ></div>
<div class="rounded-box" style="float:left;">
    <center style="color:rgb(255, 255, 255);">
        <h1>You have...</h1>
    </center>
    <center><div class="circle"><center style="color:aliceblue">{{awardnum}}</center></div></center>
    <center style="color:rgb(255, 255, 255);">
        <h1>award(s)!!</h1>
    </center>
</div>
<div class="square"></div>
<div class="rounded-box" style="float:left;">
    <center style="color:rgb(255, 255, 255);">
        <h1>You have...</h1>
    </center>
    <center><div class="circle"><center style="color:aliceblue">{{"%.1f"|format(creditnum)}}</center></div></center>
    <center style="color:rgb(255, 255, 255);">
        <h1>credit(s)!!</h1>
    </center>
</div>

  {% endblock %}

studenthelp/website/templates/job.html
{% extends "base.html" %}{% block title %}Job Information{% endblock %}{% block content  
    %} 
  <style>
    .dropdown-options{
      display: none;
      position: absolute;
      overflow: auto;
    }
  .dropdown-content {
    display: none;
    position: absolute;
    width: 120px;
    overflow: auto;
    z-index: 4;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    background-color: white
    
    
  }
  .dropdown{
    display: inline-block;
    position: relative;
  }
  .dropdown::selection .dropdown-options{
      display: block;
  }
  .test:after {
      content: '\2807';
      font-size: 25px;
    }
  
  .dropdown:hover .dropdown-content {
    display: block;
  }
  
  #SN{ 
      position:relative; 
      display: inline-block;
      top:50%; 
      left:45%; 
      width:150px; 
  
  }
  
  
  .dropdown-content a {
    display: block;
    color: #000000;
    padding: 5px;
    text-decoration: none;
  }
  
  </style>
  
  <br />
      <h3 text-align="center">Job Information</h3>
      <divlass="container">
        <form method="POST">
        </form>
      </div>  
  <br />
    <div class="table-responsive">
     <table id="data" class="table table-striped" id="SN">    
      <thead>
        <tr>
          <th>Organization</th>
          <th>Email</th>
          <th>Role</th> 
          <th>Approver</th>
          <th>Date</th>
          <th>Hours</th>
          <th>Description</th>
          <th>Options</th>
          
        </tr> 
      </thead>
      <tbody> 
        {% for job in jobs.items %}          
        <tr>
          <td><a style="color:black;">{{ job.org_name }}</a></td>
          <td><a style="color:black;">{{ job.org_email }}</a></td>
          <td><a style="color:black;">{{ job.role }}</a></td>
          <td><a style="color:black;">{{ job.approver }}</a></td>
          <td><a style="color:black;">{{ job.date.strftime('%m/%d/%Y') }}</a></td>
          <td><a style="color:black;">{{ "%.1f"|format(job.hours) }}</a></td>
          <td><a style="color:black;">{{ job.description }}</a></td>
          <td text-align="center">
            <div class="dropdown">
              <button class="btn btn secondary"><div class="test"></div></button>
              <div class="dropdown-content">
                <a href="{{url_for('views.update_job')}}?jobid={{job.job_seq}}">Update</a>
                <a href="{{url_for('views.attach_job')}}?jobid={{job.job_seq}}">Upload Document</a>
                <a href="{{url_for('views.delete_job')}}?jobid={{job.job_seq}}">Delete</a>
              </div>
            </div>
          </td>
  
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <!-- Pagination Links-->
  <div class="text-right">
    <a href="{{ url_for('views.job', page=jobs.prev_num) }}"
       class="btn btn-outline-dark 
       {% if jobs.page == 1 %}disabled{% endif %}">
        &laquo;
    </af>
  
    {% for page_num in jobs.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
  
            {% if jobs.page == page_num %}
            <a href="{{ url_for('views.job', page=page_num) }}"
               class="btn btn-dark">
                {{ page_num }}
            </a>
            {% else %}
            <a href="{{ url_for('views.job', page=page_num) }}"
               class="btn btn-outline-dark">
                {{ page_num }}
            </a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    <a href="{{ url_for('views.job', page=jobs.next_num) }}"
       class="btn btn-outline-dark 
       {% if jobs.page == jobs.pages %}disabled{% endif %}">
        &raquo;
    </a> 
   </div>
  <p class="text-right mt-3">
   
   Showing page {{ jobs.page }} of {{ jobs.pages }}
  </p>
  
  </div>
  <a href="{{url_for('views.add_job')}}" class ="btn btn-primary" id="SN">Add Job</a>
  {% endblock %}

studenthelp/website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %}{% block content 
%}
<br />
<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input 
            type="email" 
            class="form-control" 
            id="email"
            name="email" 
            placeholder="Enter email"
        />
    <br />
    <div class="form-group">
        <label for="password">Password</label>
        <input 
            type="password" 
            class="form-control" 
            id="password" 
            name="password" 
            placeholder="Enter password"
        />
    <br />
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

studenthelp/website/templates/recommendations.html
{% extends "base.html" %}{% block title %}Recommendations{% endblock %}{% block content  
    %} 
  <style>
    .dropdown-options{
      display: none;
      position: absolute;
      overflow: auto;
    }
  .dropdown-content {
    display: none;
    position: absolute;
    width: 120px;
    overflow: auto;
    z-index: 4;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    background-color: white
    
    
  }
  .dropdown{
    display: inline-block;
    position: relative;
  }
  .dropdown::selection .dropdown-options{
      display: block;
  }
  .test:after {
      content: '\2807';
      font-size: 25px;
    }
  
  .dropdown:hover .dropdown-content {
    display: block;
  }
  
  #SN{ 
      position:relative; 
      display: inline-block;
      top:50%; 
      left:45%; 
      width:150px; 
  
  }
  
  
  .dropdown-content a {
    display: block;
    color: #000000;
    padding: 5px;
    text-decoration: none;
  }
  
  </style>
  
  <br />
      <h3 text-align="center">Recommendations</h3>
      <divlass="container">
        <form method="POST">
        </form>
      </div>  
  <br />
    <div class="table-responsive">
     <table id="data" class="table table-striped" id="SN">    
      <thead>
        <tr>
          <th>Recommender Name</th>
          <th>Recommender Email</th>
          <th>Date</th>
          <th>Description</th>
          <th>Options</th>
          
        </tr> 
      </thead>
      <tbody> 
        {% for recommendation in recommendations.items %}          
        <tr>
          <td><a style="color:black;">{{ recommendation.recommend_name }}</a></td>
          <td><a style="color:black;">{{ recommendation.recommend_email }}</a></td>
          <td><a style="color:black;">{{ recommendation.date.strftime('%m/%d/%Y') }}</a></td>
          <td><a style="color:black;">{{ recommendation.description }}</a></td>
          <td text-align="center">
            <div class="dropdown">
              <button class="btn btn secondary"><div class="test"></div></button>
              <div class="dropdown-content">
                <a href="{{url_for('views.update_recommendation')}}?recommendationid={{recommendation.recommend_seq}}">Update</a>
                <a href="{{url_for('views.attach_recommendation')}}?recommendationid={{recommendation.recommend_seq}}">Upload Document</a>
                <a href="{{url_for('views.delete_recommendation')}}?recommendationid={{recommendation.recommend_seq}}">Delete</a>
              </div>
            </div>
          </td>
  
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <!-- Pagination Links-->
  <div class="text-right">
    <a href="{{ url_for('views.recommendation', page=recommendations.prev_num) }}"
       class="btn btn-outline-dark 
       {% if recommendations.page == 1 %}disabled{% endif %}">
        &laquo;
    </af>
  
    {% for page_num in recommendations.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
  
            {% if recommendations.page == page_num %}
            <a href="{{ url_for('views.recommendation', page=page_num) }}"
               class="btn btn-dark">
                {{ page_num }}
            </a>
            {% else %}
            <a href="{{ url_for('views.recommendation', page=page_num) }}"
               class="btn btn-outline-dark">
                {{ page_num }}
            </a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    <a href="{{ url_for('views.recommendation', page=recommendations.next_num) }}"
       class="btn btn-outline-dark 
       {% if recommendations.page == recommendations.pages %}disabled{% endif %}">
        &raquo;
    </a> 
   </div>
  <p class="text-right mt-3">
   
   Showing page {{ recommendations.page }} of {{ recommendations.pages }}
  </p>
  
  </div>
  <a href="{{url_for('views.add_recommendation')}}" class ="btn btn-primary" id="SN">Add Recommendations</a>
  {% endblock %}